kind: pipeline
name: default

steps:
- name: deploy
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: dmitriy5181/hugo
    tags: latest