kind: pipeline
name: default

steps:
- name: image
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: dmitriy5181/hugo
    tags: latest

- name: notify
  image: plugins/pushover
  settings:
    token:
      from_secret: pushover_token
    user:
      from_secret: pushover_user
    title: "[{{ build.status }}] {{ repo.name }}"
    message: "({{ build.branch }}) - {{ build.message }}"
  when:
    status:
      - success
      - failure