kind: pipeline
name: default

steps:
- name: image
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: dmitriy5181/hugo
    tags: latest

- name: notify
  image: drillster/drone-email
  settings:
    from: drone@prgm.xyz
    skip_verify: true
    host: prgm.xyz
    port: 25
    username:
      from_secret: email_username
    password:
      from_secret: email_password
  when:
    status:
      - success
      - failure
